name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1 # Change to your desired region

      - name: Deploy to Dev
        run: |
          sam package --template-file ./dev/lambda_sam_dev.yaml --s3-bucket demo-test-2119-prod --output-template-file packaged-lambda.yaml --profile default
          sam deploy --template-file ./dev/packaged-lambda.yaml --stack-name my-lambda-app-dev --s3-bucket demo-test-2119 --capabilities CAPABILITY_IAM

  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1 # Change to your desired region

      - name: Deploy to Prod
        run: |

          # sam package --template-file ./prod/lambda_sam_prod.yaml --s3-bucket demo-test-2119-prod --output-template-file packaged-lambda.yaml
          sam deploy --template-file ./prod/packaged-lambda.yaml --stack-name my-lambda-app-prod --capabilities CAPABILITY_IAM
